apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: juice-shop-build-and-scan

on:
  push:
    branches:
      - '**'

jobs:
  build-and-scan:
    steps:
      # 1) Clone code (using pinned alpine/git)
      - name: Clone code
        uses: docker://alpine/git:2.36.3
        shell: sh
        run: |
          git config --global --add safe.directory /cloudbees/workspace
          git clone https://github.com/jalts-808/juice.git .
          # If private, embed credentials or environment variables

      # 2) Install Node modules
      - name: Install Node modules
        uses: docker://node:18.14.2
        shell: sh
        run: |
          npm install

      # 3) Build Juice Shop (npm run build:frontend)
      - name: Build the app
        uses: docker://node:18.14.2
        shell: sh
        run: |
          npm run build:frontend

      # 4) Gitleaks secret scan
      - name: Gitleaks
        uses: docker://zricethezav/gitleaks:v8.17.0
        shell: sh
        run: |
          # Exits 0 so we don't fail if secrets are found
          gitleaks detect --exit-code 0 --redact

      # 6) Semgrep (general code analysis)
      - name: Semgrep
        # Pinned to v1.23.0 as an example; adjust if needed
        uses: docker://returntocorp/semgrep:1.23.0
        shell: sh
        run: |
          # Use the p/ci ruleset and do not fail the pipeline if findings appear
          semgrep --config p/ci --error || true

# test for syftSBOM